# left_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001
# left_gripper:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000002

left_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  solve_type: Distance  # Optional: "Speed", "Distance", or "Manip1"

left_gripper:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005