# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - left_hand_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: FollowJointTrajectory
    joints:
      - left_gripper_worm_gear_joint
    action_ns: follow_joint_trajectory
    default: true