# Dual Lidar Configuration
# Hokuyo URG Node2 and Lakibeam Lidar parameters

urg_node2:
  launch_config:
    auto_start: true
    node_name: 'urg_node2'
    scan_topic: 'front_lidar'
  ros__parameters:
    ip_address: '10.0.0.101'
    ip_port: 10940
    frame_id: 'front_lidar_link'
    calibrate_time: false
    synchronize_time: false
    publish_intensity: false
    publish_multiecho: false
    error_limit: 4
    error_reset_period: 5.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    time_offset: 0.0
    angle_min: -2.093333333333333
    angle_max: 2.093333333333333
    skip: 0
    cluster: 1

lakibeam_lidar:
  ros__parameters:
    frame_id: 'back_lidar_link'
    output_topic: 'back_lidar'
    
    inverted: false
    
    #jetson
    # hostip: '10.0.0.201' 

    #walkie pc
    hostip: '10.0.0.6' 
    
    port: '2368'
    angle_offset: 0
    sensorip: '10.0.0.102'
    scanfreq: '30'
    filter: '3'
    laser_enable: 'true'
    scan_range_start: '60'
    scan_range_stop: '300'

