hardware_config:
  # Left Arm
  left_joint1: mock
  left_joint2: mock
  left_joint3: mock
  left_joint4: mock
  left_joint5: mock
  left_joint6: mock
  left_joint7: mock
  left_gripper_worm_gear: mock # gripper joint name